### ISSUE TITLE
Error logs on fluentd-gcp-scaler every minute

### ISSUE THREAD

**Issue by peol** [qlik-oss/core-scaling#108]
```
{
    "textPayload": "error: info: {extensions v1beta1 daemonsets} \"fluentd-gcp-v3.1.0\" was not changed\n",
    "insertId": "27xggrg2zjb3vk",
    "resource": {
        "type": "container",
        "labels": {
            "pod_id": "fluentd-gcp-scaler-697b966945-c5rlm",
            "zone": "europe-west3-a",
            "project_id": "dev-prod-qlik-core",
            "cluster_name": "core-scaling",
            "container_name": "fluentd-gcp-scaler",
            "namespace_id": "kube-system",
            "instance_id": "926775557221960039"
        }
    },
    "timestamp": "2018-12-27T11:31:20Z",
    "severity": "ERROR",
    "labels": {
        "compute.googleapis.com/resource_name": "fluentd-gcp-v3.1.0-qnl66",
        "container.googleapis.com/pod_name": "fluentd-gcp-scaler-697b966945-c5rlm",
        "container.googleapis.com/stream": "stderr",
        "container.googleapis.com/namespace_name": "kube-system"
    },
    "logName": "projects/dev-prod-qlik-core/logs/fluentd-gcp-scaler",
    "receiveTimestamp": "2018-12-27T11:31:23.384932729Z"
}
```

**Comment by FredrikFolkesson** [comment]
This is an error in the gcp-fluentd-scaler where it thinks "1" CPU and 1000m cpus are different.

This will be fixed in version 1.14.0-alpha.1 of Kubernetes
https://github.com/kubernetes/kubernetes/commit/7b3946776c049f8ffea0b74fefcf03eb95e706fd#diff-946fedff16797c88e55a5d51ad7f1e59

In the meantime I have applied a scaling policy with 999m cpus to stop the log spam.

```
cat <<EOF | kubectl apply -f -
apiVersion: scalingpolicy.kope.io/v1alpha1
kind: ScalingPolicy
metadata:
  name: fluentd-gcp-scaling-policy
  namespace: kube-system
spec:
  containers:
  - name: fluentd-gcp
    resources:
      requests:
      - resource: cpu
        base: 100m
      - resource: memory
        base: 200Mi
      limits:
      - resource: memory
        base: 500Mi
      - resource: cpu
        base: 999m
EOF
```
